# Generated by Django 4.1.8 on 2023-05-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_orders_ordertype_orders_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='description',
        ),
        migrations.AddField(
            model_name='orders',
            name='adress',
            field=models.CharField(blank=True, max_length=255, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='orders',
            name='time',
            field=models.CharField(blank=True, max_length=255, verbose_name='Date'),
        ),
    ]
