# Generated by Django 4.1.8 on 2023-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_remove_orders_description_orders_adress_orders_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(blank=True, max_length=255, verbose_name='Status'),
        ),
    ]
