# Generated by Django 4.1.8 on 2023-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_remove_services_time_remove_services_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='openDescription',
            field=models.TextField(blank=True, verbose_name='Description on open'),
        ),
    ]
