# Generated by Django 4.1.8 on 2023-05-04 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_services_opendescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
