# Generated by Django 4.1.8 on 2023-05-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_successedorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(blank=True, max_length=255, verbose_name='Mark')),
                ('type', models.CharField(blank=True, max_length=255, verbose_name='Type')),
                ('count', models.IntegerField(blank=True, verbose_name='Count on store')),
                ('isAvaliable', models.BooleanField(blank=True, verbose_name='Is avaliable')),
                ('price', models.IntegerField(blank=True, verbose_name='Price')),
            ],
        ),
    ]
